import { MailerService } from '@nestjs-modules/mailer';

interface ApplicationPayload {
  fullName: string;
  age: string;
  email: string;
  phone: string;
  occupation: string;
  motivations: string[];
  challenges: string[];
  commitments: string[];
  vision: string;
  agreement: boolean;
}

export async function sendApplicationEmail(
  mailerService: MailerService,
  payload: ApplicationPayload,
) {
  const {
    fullName,
    age,
    email,
    phone,
    occupation,
    motivations,
    challenges,
    commitments,
    vision,
    agreement,
  } = payload;

  await mailerService.sendMail({
    to: process.env.EMAIL_USER,
    subject: `New Application from ${fullName}`,
    html: `
      <div style="font-family: Arial, sans-serif; padding: 20px; background: #f9f9f9; border-radius: 10px;">
        <h2 style="color: #2c3e50;">New Application Submitted</h2>
        <p><strong>Full Name:</strong> ${fullName}</p>
        <p><strong>Age:</strong> ${age}</p>
        <p><strong>Email:</strong> ${email}</p>
        <p><strong>Phone:</strong> ${phone}</p>
        <p><strong>Occupation:</strong> ${occupation}</p>
        
        <h3>Motivations</h3>
        <ul>
         ${motivations.map((m) => `<li>${m}</li>`).join('')}
        </ul>

        <h3>Challenges</h3>
        <ul>
          ${challenges.map((c) => `<li>${c}</li>`).join('')}
        </ul>

        <h3>Commitments</h3>
        <ul>
          ${commitments.map((c) => `<li>${c}</li>`).join('')}
        </ul>

        <h3>Vision</h3>
        <p>${vision}</p>

        <h3>Agreement</h3>
        <p>${agreement}</p>

        <hr style="margin-top:20px;">
        <p style="font-size: 12px; color: #888;">This email was automatically generated by the mentorship app.</p>
      </div>
    `,
  });
}
